### PR TITLE
[PATCH] darwin (Mac OS X) support for omap4boot

### PR DESCRIPTION
**Pull request by cfriedt**
Added darwin (Mac OS X) support. The file usb_darwin.c is modified from AOSP (system/core/fastboot/usb_osx.c).

### CODE REVIEW

**Comment by landonf** [comment]
I can confirm that this patch is working for me locally on Mac OS X 10.7.4, PandaBoard ES.

**Comment by estobbart** [comment]
@cfriedt Is there a problem with the ReadPipe call from the fastboot/usb_osx.c? I'm having a problem with fastboot for mac and the PandaBoard ES, I think it's a stalled ReadPipe from the usb_handle->bulkIn. Mac OS X 10.7.4 (Upgraded from 10.6)

**Comment by cfriedt** [comment]
There was a problem - it"s been a while, but I think it worked with some
usleep before the ReadPipe call was made.

©

Sent from my Android
On Jul 18, 2012 2:33 PM, "estobbart" <
reply@reply.github.com>
wrote:

**Comment by cfriedt** [comment]
I might close this PR seeing as how it's been 9y 🤣

**Pull request closed without merging**
